
package gui;

import java.awt.Color;
import root.*;

/**
 *
 * @author mctes
 */
public class Brett extends javax.swing.JFrame {
    
    private boolean istZugbeginn = true;

    /**
     * Creates new form Brett
     */
    public Brett() {
        initComponents();
        
        getContentPane().removeAll();
        
        boolean schwarz = true;
        
        for (int z = 0; z < feld.length; z++) {
            for (int sp = 0; sp < feld[z].length; sp++) {
                Feld f = new Feld(this, schwarz);
                feld[z][sp] = f;
                f.addActionListener(fl);
                f.setBackground(schwarz ? Color.darkGray : Color.lightGray);
                
                if (schwarz) {
                    if (z <= 3) {
                        f.setStein(new Einfach(f, false));
                    } else if (z >= 6) {
                        f.setStein(new Einfach(f, true));
                    }
                }
                
                jPanel1.add(f);
                schwarz = !schwarz;
            }
            schwarz = !schwarz;
        }
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        pack();
    }
    
    public boolean getZugbeginn() {
        return istZugbeginn;
    }
    
    public void merkeBeginn() {
        istZugbeginn = false;
    }
    
    public void merkeEnde() {
        istZugbeginn = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.GridLayout(10, 10));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brett().setVisible(true);
            }
        });
    }
    
    private Feld[][] feld = new Feld[10][10];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private class FeldListener implements java.awt.event.ActionListener {
        
        Stein st = null;

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Feld f = null;
            for (int z = 0; z < feld.length; z++) {
                for (int sp = 0; sp < feld.length; sp++) {
                    if (evt.getSource() == feld[z][sp]) {
                        System.out.println("Feld " + z + ", " + sp + " geklickt");
                        f = feld[z][sp];
                        break;
                    }
                }
            }
            
            if (getZugbeginn()) {
                st = f.getStein();
                f.wegStein();
            } else {
                f.setStein(st);
            }
        }
    }
    
    FeldListener fl = new FeldListener();
}
